version: "3.8"

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./apps/web:/usr/src/app
      - /usr/src/app/node_modules
